export const tdrexAssetsData: any[] = [
  {
    chainId: 1,
    decimals: 18,
    symbol: 'TP26',
    name: 'Tesouro Prefixado 2026',
    isNative: true,
    isToken: true,
    address: 'a',
    wrapped: {
      chainId: 1,
      decimals: 18,
      symbol: 'TP26',
      name: 'Tesouro Prefixado 2026',
      isNative: false,
      isToken: true,
      address: 'a',
    },
  },
  {
    chainId: 2,
    decimals: 18,
    symbol: 'TP29',
    name: 'Tesouro Prefixado 2029',
    isNative: false,
    isToken: true,
    address: 'b',
    wrapped: {
      chainId: 2,
      decimals: 18,
      symbol: 'TP29',
      name: 'Tesouro Prefixado 2029',
      isNative: false,
      isToken: true,
      address: 'b',
    },
  },
  {
    chainId: 3,
    decimals: 18,
    symbol: 'TS26',
    name: 'Tesouro Selic 2026',
    isNative: false,
    isToken: true,
    address: 'c',
    wrapped: {
      chainId: 3,
      decimals: 18,
      symbol: 'TS26',
      name: 'Tesouro Selic 2026',
      isNative: false,
      isToken: true,
      address: 'c',
    },
  },
  {
    chainId: 4,
    decimals: 18,
    symbol: 'TS29',
    name: 'Tesouro Selic 2029',
    isNative: false,
    isToken: true,
    address: 'd',
    wrapped: {
      chainId: 4,
      decimals: 18,
      symbol: 'TS29',
      name: 'Tesouro Selic 2029',
      isNative: false,
      isToken: true,
      address: 'd',
    },
  },
]

/**
 * CBDCs: Colômbia, Real Digital, Hong Kong, Japão, Uruguai
 *
 */
export const tdrexCBDCsData: any[] = [
  {
    chainId: 1,
    decimals: 18,
    symbol: 'COL',
    name: 'Colômbia',
    isNative: true,
    isToken: true,
    address: 'e',
    wrapped: {
      chainId: 1,
      decimals: 18,
      symbol: 'COL',
      name: 'Colômbia',
      isNative: false,
      isToken: true,
      address: 'e',
    },
  },
  {
    chainId: 2,
    decimals: 18,
    symbol: 'DREX',
    name: 'Real Digital',
    isNative: false,
    isToken: true,
    address: 'f',
    wrapped: {
      chainId: 2,
      decimals: 18,
      symbol: 'DREX',
      name: 'Real Digital',
      isNative: false,
      isToken: true,
      address: 'f',
    },
  },
  {
    chainId: 3,
    decimals: 18,
    symbol: 'HKG',
    name: 'Hong Kong',
    isNative: false,
    isToken: true,
    address: 'g',
    wrapped: {
      chainId: 3,
      decimals: 18,
      symbol: 'HKG',
      name: 'Hong Kong',
      isNative: false,
      isToken: true,
      address: 'g',
    },
  },
  {
    chainId: 4,
    decimals: 18,
    symbol: 'JPY',
    name: 'Japão',
    isNative: false,
    isToken: true,
    address: 'h',
    wrapped: {
      chainId: 4,
      decimals: 18,
      symbol: 'JPY',
      name: 'Japão',
      isNative: false,
      isToken: true,
      address: 'h',
    },
  },
  {
    chainId: 5,
    decimals: 18,
    symbol: 'URY',
    name: 'Uruguai',
    isNative: false,
    isToken: true,
    address: 'i',
    wrapped: {
      chainId: 5,
      decimals: 18,
      symbol: 'URY',
      name: 'Uruguai',
      isNative: false,
      isToken: true,
      address: 'i',
    },
  },
]
